[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F429ZITx with your chip as listed in `probe-rs chip list`
runner = "picotool load -u -v -x -t elf"
# runner = ""

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "trace"
